services:
  mongodb:
    image: mongo:8.0
    container_name: ecommerce-mongodb

    ports:
      - "127.0.0.1:27017:27017"

    environment:
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: orders_db

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  mongo_data: