spring.application.name=order.management

# MongoDB configuration
spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017/orders_db?authSource=admin
spring.main.banner-mode=off