spring.application.name=order.management

# MongoDB configuration
spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USER:admin}:${MONGO_ROOT_PASSWORD:admin123}@127.0.0.1:27017/orders_db?authSource=admin
spring.main.banner-mode=off

# Feign Clients - External Liverpool APIs
liverpool.api.orders.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/pedidos
liverpool.api.items.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/items