spring.application.name=order.management
spring.docker.compose.enabled=false

# MongoDB configuration
spring.mongodb.uri=${MONGO_URI}
spring.main.banner-mode=off

# Feign Clients - External Liverpool APIs
liverpool.api.orders.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/pedidos
liverpool.api.items.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/items

#App port forwarding for cloud
server.port=${PORT:8080}